services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatgpt-retrieval-plugin-app
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000
    environment:
      - DATASTORE=mongodb
      - BEARER_TOKEN=${BEARER_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGODB_URI=${MONGODB_URI}
      - EMBEDDING_DIMENSION=${EMBEDDING_DIMENSION:-256}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-3-large}
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo-atlas

  # mongo:
  #   image: mongo:latest
  #   container_name: chatgpt-retrieval-plugin-mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db

  mongo-atlas:
    image: mongodb/atlas
    privileged: true
    volumes:
      # - data-cni:/etc/cni
      # - data-containers:/var/lib/containers
      - ./entrypointd.sh:/entrypoint.sh
      - mongo_data:/data/db
      # - ./src/:/src
    entrypoint: ["/entrypoint.sh"]
    ports:
      - 27017:27017
    env_file:
      - .env

volumes:
  mongo_data:
